name: Deploy React App to Object Storage

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: test
        type: choice
        options:
          - production
          - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set environment variables
        id: set-vars
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            echo "VITE_API_URL=${{ secrets.VITE_API_URL_PROD }}" >> $GITHUB_ENV
            echo "::set-output name=bucket::frontend-neurointegration-sprints"
          else
            echo "VITE_API_URL=${{ secrets.VITE_API_URL_TEST }}" >> $GITHUB_ENV
            echo "::set-output name=bucket::frontend-neurointegration-sprints-test"
          fi

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip awscli==1.35.0
          aws --version

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name: Clear bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws --endpoint-url=https://storage.yandexcloud.net s3 rm --recursive s3://${{ steps.set-vars.outputs.bucket }}

      - name: Upload to Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws --endpoint-url=https://storage.yandexcloud.net s3 cp --recursive dist/ s3://${{ steps.set-vars.outputs.bucket }}
